function [dqdx1, dqdx2, dqdu] = deriv_qpumpe(x1, x2, u, pump, config)
    rho = x1 / config.a1 + config.c_hat - config.d;
    
    dqdx1 = u * pump.b * deriv_smooth_sqrt(rho) * ...
        sig_minus_var(x1, config.a1*(config.zpump+config.zH)) * ...
        sig_minus_var(-x2, -config.a2*config.zveg) + ...
        u * pump.b * smooth_sqrt(rho) * ...
        deriv_sig_minus_var(x1, config.a1*(config.zpump+config.zH), config.epsilon) * ...
        sig_minus_var(-x2, -config.a2*config.zveg);
    
    dqdx2 = u * pump.b * smooth_sqrt(rho) * ...
        sig_minus_var(x1, config.a1*(config.zpump+config.zH)) * ...
        deriv_sig_minus_var(-x2, -config.a2*config.zveg, config.epsilon);
    
    dqdu = pump.b * sig_minus_var(x1, config.a1*(config.zpump+config.zH)) * ...
        sig_minus_var(-x2, -config.a2*config.zveg);
    
end

